# This is a basic workflow to help you get started with Actions

name: Check houses(Common).

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: "*/10 * * * *" 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write  # This line ensures the workflow has permission to create issues
  actions: write
  contents: read

jobs:
  check-time-range:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      - name: Check time range
        run: |
          # Get the current hour in UTC
          HOUR=$(date +"%H")

          echo "HOUR:${HOUR}"
          
          # Check if outside 8 AM to 10 PM JST range
          # UTC 22 PM to 13 PM(14,15)
          if [ $HOUR -lt 22 ] && [ $HOUR -gt 14 ]; then
            echo "Current time is outside the schedule range. Exiting..."
            exit 1
          fi
          
  call-callee:
    runs-on: ubuntu-latest
    needs: check-time-range
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Trigger Callee Workflow for Each JSON Item
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq -c '.[]' .github/input_parameter_common_priority.json | while read i; do
            TYPE=$(echo $i | jq -r '.type')
            ENCODED_HOUSE_NAME=$(echo $i | jq -r '.encodedHouseName')
            HOUSE_NAME=$(echo $i | jq -r '.houseName')
            GREP_KEY=$(echo $i | jq -r '.grepKey')
            HOME_PAGE=$(echo $i | jq -r '.homePage')

            # Use GitHub API to trigger the workflow_dispatch event
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/callee_single_building.yml/dispatches \
              -d '{"ref":"main", "inputs": {"type":"'"$TYPE"'", "houseName":"'"$HOUSE_NAME"'", "encodedHouseName":"'"$ENCODED_HOUSE_NAME"'", "grepKey":"'"$GREP_KEY"'", "homePage":"'"$HOME_PAGE"'"}}'
          done
